'use strict';

            var lodash = require('lodash');
            var bcrypt = require('bcryptjs');
            
            exports.loadModel = function loadModel() {
                const serverfunction = global.app.orm.sequelize.define('serverfunction',
                    lodash.extend({}, global.app.orm.mixins.attributes, {
                        
    id: {
      autoIncrement: true,
      type: global.app.orm.Sequelize.INTEGER,
      allowNull: false,
      primaryKey: true
    },
    description: {
      type: global.app.orm.Sequelize.TEXT,
      allowNull: true
    },
    name: {
      type: global.app.orm.Sequelize.STRING(255),
      allowNull: true
    },
    route: {
      type: global.app.orm.Sequelize.TEXT,
      allowNull: false
    },
    method: {
      type: global.app.orm.Sequelize.TEXT,
      allowNull: false
    },
    free: {
      type: global.app.orm.Sequelize.INTEGER,
      allowNull: false,
      defaultValue: 0
    },
    associatedModel: {
      type: global.app.orm.Sequelize.TEXT,
      allowNull: true
    }
  ,
    createdAt: {
      type: global.app.orm.Sequelize.DATE,
      allowNull: false
    },
    updatedAt: {
      type: global.app.orm.Sequelize.DATE,
      allowNull: false
    },
    deletedAt: {
      type: global.app.orm.Sequelize.DATE,
      allowNull: true
    }
        }), {
            timestamps: true,
            comment: 'A example model.',
            freezeTableName: true,
            tableName: 'serverfunction',
            hooks: {}
        });
        serverfunction.associate = function() {
            var models = global.app.orm.sequelize.models;
                                    models.serverfunction.hasMany(models.log, { foreignKey: 'serverFunctionId', as: 'logs' });
                                    models.serverfunction.hasMany(models.roleserverfunction, { foreignKey: 'serverFunctionId', as: 'roleserverfunctions' });
                    }
                };
                exports.arrayRelations = [
                    {
                    typeRelation:'hasMany',
                    nameModel:'log',
                    nameRelation:'logs'
                },
                    {
                    typeRelation:'hasMany',
                    nameModel:'roleserverfunction',
                    nameRelation:'roleserverfunctions'
                },
        ]
    
    exports.arrayAttributes = ['id','description','name','route','method','free','associatedModel','createdAt','updatedAt','deletedAt']
                 exports.permissions = [
                            {
                            associatedModel:'bank_data',
                            route:'/v1/bank_data',
                            method:'PUT',
                            rol:9,
                            canAll:'yes'
                        },
                            {
                            associatedModel:'bank_data',
                            route:'/v1/bank_data',
                            method:'POST',
                            rol:9,
                            canAll:'yes'
                        },
                            {
                            associatedModel:'bank_data',
                            route:'/v1/bank_data',
                            method:'DELETE',
                            rol:9,
                            canAll:'yes'
                        },
                            {
                            associatedModel:'bank_data',
                            route:'/v1/bank_data',
                            method:'PATCH',
                            rol:9,
                            canAll:'yes'
                        },
                            {
                            associatedModel:'country',
                            route:'/v1/country',
                            method:'PUT',
                            rol:9,
                            canAll:'yes'
                        },
                            {
                            associatedModel:'country',
                            route:'/v1/country',
                            method:'POST',
                            rol:9,
                            canAll:'yes'
                        },
                            {
                            associatedModel:'country',
                            route:'/v1/country',
                            method:'DELETE',
                            rol:9,
                            canAll:'yes'
                        },
                            {
                            associatedModel:'country',
                            route:'/v1/country',
                            method:'PATCH',
                            rol:9,
                            canAll:'yes'
                        },
                            {
                            associatedModel:'mipyme',
                            route:'/v1/mipyme',
                            method:'PUT',
                            rol:9,
                            canAll:'yes'
                        },
                            {
                            associatedModel:'mipyme',
                            route:'/v1/mipyme',
                            method:'POST',
                            rol:9,
                            canAll:'yes'
                        },
                            {
                            associatedModel:'mipyme',
                            route:'/v1/mipyme',
                            method:'DELETE',
                            rol:9,
                            canAll:'yes'
                        },
                            {
                            associatedModel:'mipyme',
                            route:'/v1/mipyme',
                            method:'PATCH',
                            rol:9,
                            canAll:'yes'
                        },
                            {
                            associatedModel:'document',
                            route:'/v1/document',
                            method:'PUT',
                            rol:9,
                            canAll:'yes'
                        },
                            {
                            associatedModel:'document',
                            route:'/v1/document',
                            method:'POST',
                            rol:9,
                            canAll:'yes'
                        },
                            {
                            associatedModel:'document',
                            route:'/v1/document',
                            method:'DELETE',
                            rol:9,
                            canAll:'yes'
                        },
                            {
                            associatedModel:'document',
                            route:'/v1/document',
                            method:'PATCH',
                            rol:9,
                            canAll:'yes'
                        },
                            {
                            associatedModel:'log',
                            route:'/v1/log',
                            method:'PUT',
                            rol:9,
                            canAll:'yes'
                        },
                            {
                            associatedModel:'log',
                            route:'/v1/log',
                            method:'POST',
                            rol:9,
                            canAll:'yes'
                        },
                            {
                            associatedModel:'log',
                            route:'/v1/log',
                            method:'DELETE',
                            rol:9,
                            canAll:'yes'
                        },
                            {
                            associatedModel:'log',
                            route:'/v1/log',
                            method:'PATCH',
                            rol:9,
                            canAll:'yes'
                        },
                            {
                            associatedModel:'person',
                            route:'/v1/person',
                            method:'PUT',
                            rol:9,
                            canAll:'yes'
                        },
                            {
                            associatedModel:'person',
                            route:'/v1/person',
                            method:'POST',
                            rol:9,
                            canAll:'yes'
                        },
                            {
                            associatedModel:'person',
                            route:'/v1/person',
                            method:'DELETE',
                            rol:9,
                            canAll:'yes'
                        },
                            {
                            associatedModel:'person',
                            route:'/v1/person',
                            method:'PATCH',
                            rol:9,
                            canAll:'yes'
                        },
                            {
                            associatedModel:'role',
                            route:'/v1/role',
                            method:'PUT',
                            rol:9,
                            canAll:'yes'
                        },
                            {
                            associatedModel:'role',
                            route:'/v1/role',
                            method:'POST',
                            rol:9,
                            canAll:'yes'
                        },
                            {
                            associatedModel:'role',
                            route:'/v1/role',
                            method:'DELETE',
                            rol:9,
                            canAll:'yes'
                        },
                            {
                            associatedModel:'role',
                            route:'/v1/role',
                            method:'PATCH',
                            rol:9,
                            canAll:'yes'
                        },
                            {
                            associatedModel:'roleperson',
                            route:'/v1/roleperson',
                            method:'PUT',
                            rol:9,
                            canAll:'yes'
                        },
                            {
                            associatedModel:'roleperson',
                            route:'/v1/roleperson',
                            method:'POST',
                            rol:9,
                            canAll:'yes'
                        },
                            {
                            associatedModel:'roleperson',
                            route:'/v1/roleperson',
                            method:'DELETE',
                            rol:9,
                            canAll:'yes'
                        },
                            {
                            associatedModel:'roleperson',
                            route:'/v1/roleperson',
                            method:'PATCH',
                            rol:9,
                            canAll:'yes'
                        },
                            {
                            associatedModel:'roleserverfunction',
                            route:'/v1/roleserverfunction',
                            method:'PUT',
                            rol:9,
                            canAll:'yes'
                        },
                            {
                            associatedModel:'roleserverfunction',
                            route:'/v1/roleserverfunction',
                            method:'POST',
                            rol:9,
                            canAll:'yes'
                        },
                            {
                            associatedModel:'roleserverfunction',
                            route:'/v1/roleserverfunction',
                            method:'DELETE',
                            rol:9,
                            canAll:'yes'
                        },
                            {
                            associatedModel:'roleserverfunction',
                            route:'/v1/roleserverfunction',
                            method:'PATCH',
                            rol:9,
                            canAll:'yes'
                        },
                            {
                            associatedModel:'serverfunction',
                            route:'/v1/serverfunction',
                            method:'PUT',
                            rol:9,
                            canAll:'yes'
                        },
                            {
                            associatedModel:'serverfunction',
                            route:'/v1/serverfunction',
                            method:'POST',
                            rol:9,
                            canAll:'yes'
                        },
                            {
                            associatedModel:'serverfunction',
                            route:'/v1/serverfunction',
                            method:'DELETE',
                            rol:9,
                            canAll:'yes'
                        },
                            {
                            associatedModel:'serverfunction',
                            route:'/v1/serverfunction',
                            method:'PATCH',
                            rol:9,
                            canAll:'yes'
                        },
                            {
                            associatedModel:'state',
                            route:'/v1/state',
                            method:'PUT',
                            rol:9,
                            canAll:'yes'
                        },
                            {
                            associatedModel:'state',
                            route:'/v1/state',
                            method:'POST',
                            rol:9,
                            canAll:'yes'
                        },
                            {
                            associatedModel:'state',
                            route:'/v1/state',
                            method:'DELETE',
                            rol:9,
                            canAll:'yes'
                        },
                            {
                            associatedModel:'state',
                            route:'/v1/state',
                            method:'PATCH',
                            rol:9,
                            canAll:'yes'
                        },
                            {
                            associatedModel:'city',
                            route:'/v1/city',
                            method:'PUT',
                            rol:9,
                            canAll:'yes'
                        },
                            {
                            associatedModel:'city',
                            route:'/v1/city',
                            method:'POST',
                            rol:9,
                            canAll:'yes'
                        },
                            {
                            associatedModel:'city',
                            route:'/v1/city',
                            method:'DELETE',
                            rol:9,
                            canAll:'yes'
                        },
                            {
                            associatedModel:'city',
                            route:'/v1/city',
                            method:'PATCH',
                            rol:9,
                            canAll:'yes'
                        },
                            {
                            associatedModel:'bank_data',
                            route:'/v1/bank_data',
                            method:'PUT',
                            rol:7,
                            canAll:'yes'
                        },
                            {
                            associatedModel:'bank_data',
                            route:'/v1/bank_data',
                            method:'POST',
                            rol:7,
                            canAll:'yes'
                        },
                            {
                            associatedModel:'bank_data',
                            route:'/v1/bank_data',
                            method:'DELETE',
                            rol:7,
                            canAll:'yes'
                        },
                            {
                            associatedModel:'bank_data',
                            route:'/v1/bank_data',
                            method:'PATCH',
                            rol:7,
                            canAll:'yes'
                        },
                            {
                            associatedModel:'country',
                            route:'/v1/country',
                            method:'PUT',
                            rol:7,
                            canAll:'yes'
                        },
                            {
                            associatedModel:'mipyme',
                            route:'/v1/mipyme',
                            method:'PUT',
                            rol:7,
                            canAll:'yes'
                        },
                            {
                            associatedModel:'mipyme',
                            route:'/v1/mipyme',
                            method:'POST',
                            rol:7,
                            canAll:'yes'
                        },
                            {
                            associatedModel:'mipyme',
                            route:'/v1/mipyme',
                            method:'DELETE',
                            rol:7,
                            canAll:'yes'
                        },
                            {
                            associatedModel:'mipyme',
                            route:'/v1/mipyme',
                            method:'PATCH',
                            rol:7,
                            canAll:'yes'
                        },
                            {
                            associatedModel:'document',
                            route:'/v1/document',
                            method:'PUT',
                            rol:7,
                            canAll:'yes'
                        },
                            {
                            associatedModel:'document',
                            route:'/v1/document',
                            method:'POST',
                            rol:7,
                            canAll:'yes'
                        },
                            {
                            associatedModel:'document',
                            route:'/v1/document',
                            method:'DELETE',
                            rol:7,
                            canAll:'yes'
                        },
                            {
                            associatedModel:'document',
                            route:'/v1/document',
                            method:'PATCH',
                            rol:7,
                            canAll:'yes'
                        },
                            {
                            associatedModel:'log',
                            route:'/v1/log',
                            method:'PUT',
                            rol:7,
                            canAll:'yes'
                        },
                            {
                            associatedModel:'person',
                            route:'/v1/person',
                            method:'PUT',
                            rol:7,
                            canAll:'yes'
                        },
                            {
                            associatedModel:'person',
                            route:'/v1/person',
                            method:'POST',
                            rol:7,
                            canAll:'yes'
                        },
                            {
                            associatedModel:'person',
                            route:'/v1/person',
                            method:'DELETE',
                            rol:7,
                            canAll:'yes'
                        },
                            {
                            associatedModel:'person',
                            route:'/v1/person',
                            method:'PATCH',
                            rol:7,
                            canAll:'yes'
                        },
                            {
                            associatedModel:'role',
                            route:'/v1/role',
                            method:'PUT',
                            rol:7,
                            canAll:'yes'
                        },
                            {
                            associatedModel:'roleperson',
                            route:'/v1/roleperson',
                            method:'PUT',
                            rol:7,
                            canAll:'yes'
                        },
                            {
                            associatedModel:'roleperson',
                            route:'/v1/roleperson',
                            method:'POST',
                            rol:7,
                            canAll:'yes'
                        },
                            {
                            associatedModel:'roleperson',
                            route:'/v1/roleperson',
                            method:'DELETE',
                            rol:7,
                            canAll:'yes'
                        },
                            {
                            associatedModel:'roleperson',
                            route:'/v1/roleperson',
                            method:'PATCH',
                            rol:7,
                            canAll:'yes'
                        },
                            {
                            associatedModel:'roleserverfunction',
                            route:'/v1/roleserverfunction',
                            method:'PUT',
                            rol:7,
                            canAll:'yes'
                        },
                            {
                            associatedModel:'serverfunction',
                            route:'/v1/serverfunction',
                            method:'PUT',
                            rol:7,
                            canAll:'yes'
                        },
                            {
                            associatedModel:'state',
                            route:'/v1/state',
                            method:'PUT',
                            rol:7,
                            canAll:'yes'
                        },
                            {
                            associatedModel:'city',
                            route:'/v1/city',
                            method:'PUT',
                            rol:7,
                            canAll:'yes'
                        },
                            {
                            associatedModel:'bank_data',
                            route:'/v1/bank_data',
                            method:'PUT',
                            rol:10,
                            canAll:'no'
                        },
                            {
                            associatedModel:'bank_data',
                            route:'/v1/bank_data',
                            method:'POST',
                            rol:10,
                            canAll:'no'
                        },
                            {
                            associatedModel:'bank_data',
                            route:'/v1/bank_data',
                            method:'DELETE',
                            rol:10,
                            canAll:'no'
                        },
                            {
                            associatedModel:'bank_data',
                            route:'/v1/bank_data',
                            method:'PATCH',
                            rol:10,
                            canAll:'no'
                        },
                            {
                            associatedModel:'country',
                            route:'/v1/country',
                            method:'PUT',
                            rol:10,
                            canAll:'yes'
                        },
                            {
                            associatedModel:'mipyme',
                            route:'/v1/mipyme',
                            method:'PUT',
                            rol:10,
                            canAll:'no'
                        },
                            {
                            associatedModel:'mipyme',
                            route:'/v1/mipyme',
                            method:'POST',
                            rol:10,
                            canAll:'no'
                        },
                            {
                            associatedModel:'mipyme',
                            route:'/v1/mipyme',
                            method:'DELETE',
                            rol:10,
                            canAll:'no'
                        },
                            {
                            associatedModel:'mipyme',
                            route:'/v1/mipyme',
                            method:'PATCH',
                            rol:10,
                            canAll:'no'
                        },
                            {
                            associatedModel:'document',
                            route:'/v1/document',
                            method:'PUT',
                            rol:10,
                            canAll:'no'
                        },
                            {
                            associatedModel:'document',
                            route:'/v1/document',
                            method:'POST',
                            rol:10,
                            canAll:'no'
                        },
                            {
                            associatedModel:'document',
                            route:'/v1/document',
                            method:'DELETE',
                            rol:10,
                            canAll:'no'
                        },
                            {
                            associatedModel:'document',
                            route:'/v1/document',
                            method:'PATCH',
                            rol:10,
                            canAll:'no'
                        },
                            {
                            associatedModel:'person',
                            route:'/v1/person',
                            method:'PUT',
                            rol:10,
                            canAll:'no'
                        },
                            {
                            associatedModel:'person',
                            route:'/v1/person',
                            method:'DELETE',
                            rol:10,
                            canAll:'no'
                        },
                            {
                            associatedModel:'person',
                            route:'/v1/person',
                            method:'PATCH',
                            rol:10,
                            canAll:'no'
                        },
                            {
                            associatedModel:'state',
                            route:'/v1/state',
                            method:'PUT',
                            rol:10,
                            canAll:'yes'
                        },
                            {
                            associatedModel:'city',
                            route:'/v1/city',
                            method:'PUT',
                            rol:10,
                            canAll:'yes'
                        },
        ]
    